### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by xudianc** [QingdaoU/OnlineJudgeFE#1]
`../src/contextify.cc:150:16: erreur : ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,`
And yeah this function has been removed after deprecation. Now we need to use "SetAccessCheckCallback".

As I don't know node at all. I don't know how to fix it.

**Comment by virusdefender** [comment]
What is ur nodejs version? 

I have no idea about this issue, maybe you can refer https://github.com/fuse-box/angular2-example/issues/13

**Comment by xudianc** [comment]
v7.7.4

**Comment by virusdefender** [comment]
最近重新看了下这个问题，你尝试使用node 6.6试下。

**Comment by xudianc** [comment]
嗯，

**Comment by zema1** [comment]
OJ前端用的simditor-markdown官方已经不维护了，高版本node install会出错，node 6.2.2可以正常安装，以后可能会考虑换掉这个编辑器
