### ISSUE TITLE
问题详情页 渲染兼容

### ISSUE THREAD

**Issue by g0ink** [QingdaoU/OnlineJudgeFE#104]
当请求 `/api/problem?problem_id=xxx` 时，
若后端版本较低，未下发`io_mode` dict，将导致问题详情页**整个页面无法正常渲染**。

**Comment by virusdefender** [comment]
为啥前后端还会有兼容性问题啊

**Comment by g0ink** [comment]
> 为啥前后端还会有兼容性问题啊

有个老倒霉蛋在做毕设，重写了后端，按照旧版本下发json无法正常渲染，看console看秃了头。。。
我理解即使没有下发也应该能正常渲染下发了的一部分字段吧。。。

**Comment by virusdefender** [comment]
自己改吧，看上去不难
