### ISSUE TITLE
网页手动刷新后会出现左上角logo无法正常显示的

### ISSUE THREAD

**Issue by IanNIE2013** [QingdaoU/OnlineJudgeFE#133]
会出现这个
<img width="71" alt="屏幕截图 2024-04-15 213720" src="https://github.com/QingdaoU/OnlineJudge/assets/162113196/17ba784d-105c-496b-9585-1026f97a8f70">
但是实际应该是这个
<img width="171" alt="屏幕截图 2024-04-15 213749" src="https://github.com/QingdaoU/OnlineJudge/assets/162113196/6e17dae5-bfea-45f1-a438-19da4cec0732">
我找到了问题，出现在
<img width="436" alt="屏幕截图 2024-04-15 213914" src="https://github.com/QingdaoU/OnlineJudge/assets/162113196/9cbc9894-e33d-4139-b26b-7b709257d4fa">
应该是这样的：
```html
<img data-v-0b9f3f56="" data-v-90f51026="" src="/public/website/kechuangoj.PNG" height="55">
```
但实际是这样的：
```html
<img data-v-0b9f3f56="" data-v-90f51026="" src="public/website/kechuangoj.PNG" height="55">
```
有没有大佬出面解决一下？

**Comment by IanNIE2013** [comment]
而且主要的问题是不手动刷新就不会有这个问题，手动刷新问题一下就暴露了。不好解决

**Comment by mikucat0309** [comment]
源码没有放图，这是自己改的嘛？
https://github.com/QingdaoU/OnlineJudgeFE/blob/44fa4744c21ad5098c21b1c5d974f4413a171319/src/pages/oj/components/NavBar.vue#L4

**Comment by IanNIE2013** [comment]
> 源码没有放图，这是自己改的嘛？
> 
> https://github.com/QingdaoU/OnlineJudgeFE/blob/44fa4744c21ad5098c21b1c5d974f4413a171319/src/pages/oj/components/NavBar.vue#L4

哦，不是不是，我是个初学者，我是看的进入网页之后Ctrl+Shift+C之后的那个“检查”，不是源码，我不是太会看源码

**Comment by IanNIE2013** [comment]
> 源码没有放图，这是自己改的嘛？
> 
> https://github.com/QingdaoU/OnlineJudgeFE/blob/44fa4744c21ad5098c21b1c5d974f4413a171319/src/pages/oj/components/NavBar.vue#L4

但总之有个奇怪的问题

**Comment by IanNIE2013** [comment]
> 源码没有放图，这是自己改的嘛？
> 
> https://github.com/QingdaoU/OnlineJudgeFE/blob/44fa4744c21ad5098c21b1c5d974f4413a171319/src/pages/oj/components/NavBar.vue#L4

没有放图？那我不知道，我在检查中看的是放了图的

**Comment by mikucat0309** [comment]
那就要问你们那个 OJ 当初谁修改了，原版青岛 OJ 左上角是纯文字没错
