### ISSUE TITLE
修改前端问题

### ISSUE THREAD

**Issue by aljw33** [QingdaoU/OnlineJudgeFE#134]
修改前端那块，nodejs v8.12.0 版本无法正常 install，如 npm install （多是警告及bug）、、、npm run build、、等等，在阿里云Ubuntu 22.04 服务器上

**Comment by mikucat0309** [comment]
以前的编译方式已不可考，我也没成功过，卡在下载依赖 😅
目前确定能成功的是用 Node.js 16 + Yarn

```bash
export NODE_ENV=production
yarn install
yarn run build:dll
yarn run build
```
