### ISSUE TITLE
dockerfile (probably) placed in wrong place and missing ADD statement

### ISSUE THREAD

**Issue by leo-wsy** [QingdaoU/OnlineJudgeFE#18]
you might want to place that at the root of project, and by the way, is that really okay to have no ADD statement (resulting just create a few empty folders to the root of docker img so that container instanced won't start) in dockerfile???

**Comment by virusdefender** [comment]
You are right, there is something unreasonable with `deploy` dir, however it is only used for local development. 

The scripts and development instructions will be updated once we have free time.

The real Dockerfile is `https://github.com/QingdaoU/OnlineJudge/blob/master/Dockerfile#L14`
