### ISSUE TITLE
onlinejudgeFE组件无法渲染

### ISSUE THREAD

**Issue by hirCodd** [QingdaoU/OnlineJudgeFE#21]
配置本地开发环境时，出现了下拉无法响应的问题，包括login之后，账户的下拉也无法响应。

**Comment by virusdefender** [comment]
看下你的开发者工具的 console 中有没有报错

**Comment by hirCodd** [comment]
`The connection to http://localhost:8080/__webpack_hmr was interrupted while the page was loading.`
只是出现了连接中断,可是并没有改动过原来的前端。

**Comment by virusdefender** [comment]
我说浏览器开发者工具的日志

**Comment by hirCodd** [comment]
![image](https://user-images.githubusercontent.com/20184263/38969418-c7fcacb2-43c2-11e8-9a34-a4daa26fe1b7.png)

**Comment by virusdefender** [comment]
你用 Chrome 试试呢

**Comment by hirCodd** [comment]
chrome中console就什么都没有了...

**Comment by hirCodd** [comment]
![image](https://user-images.githubusercontent.com/20184263/38969932-43c10ee0-43c5-11e8-9963-dbb08c41bbff.png)

**Comment by virusdefender** [comment]
那 network 中有没有异常的请求的，比如 server error 或者返回了不正常的东西

**Comment by virusdefender** [comment]
或者 proxy 地址写 https://qduoj.com 看看有问题么

**Comment by hirCodd** [comment]
那我换了试一下，network是没有什么异常的

**Comment by hirCodd** [comment]
这里的proxy地址请问是在那里设置呢

**Comment by hirCodd** [comment]
![image](https://user-images.githubusercontent.com/20184263/39029622-4e356bf8-448f-11e8-87e1-be74bbd0349a.png)

这个是我将proxy设置为https://qduoj.com 后的，依旧不正常。
![image](https://user-images.githubusercontent.com/20184263/39029927-304cbdc4-4491-11e8-8298-5f2d3c1e435a.png)
这是network的截图，也是正常，都获取到数据了

**Comment by virusdefender** [comment]
这个就有些玄学问题了，我本地测试没问题。尝试删除 node_modules 然后重新 npm install 和 npm run dev

**Comment by hirCodd** [comment]
我已经找到了原因，在problemList可以把两个width都注释了，没有什么错误跟异常，下拉菜单不能用的原因是ivivew的原因，用的是2.x，但是语法是1.x的，可能这个只是我个人原因，改了部分前端的语法,就搞定了。非常麻烦了，谢谢啊。

**Comment by eagle705** [comment]
@hirCodd @virusdefender 
I have a similar issue. 
I clone the lastest version of OnlineJudgeFE and I found out that
"Problem List, LogOut, and Admin page" doesn't work as Deploy version...

How can I fix it?

**Comment by eagle705** [comment]
+++++) I update my node v6 to v8 with npm 
it success :)

**Comment by virusdefender** [comment]
@hirCodd 你是自己修改过前端么？也有可能是屏幕分辨率导致的？

**Comment by virusdefender** [comment]
@eagle705 but using node v8 may cause some errors while running npm install

**Comment by hirCodd** [comment]
还没有改过，屏幕分辨率能影响下拉菜单？我都是默认的ubuntu的设置...

**Comment by hirCodd** [comment]
屏幕分辨率是1920*1080...
![image](https://user-images.githubusercontent.com/20184263/39045958-046a45ec-44c7-11e8-8e63-f3a6ef9ae403.png)
这个是我改之前说的width之后的样子，就能正常显示了。

**Comment by hirCodd** [comment]
@virusdefender 可是改了下拉组件还是无法生效时为啥...

**Comment by hirCodd** [comment]
@virusdefender 我已经fix这个bug了，导航栏的问题是因为实际高度超过了60px，而使用了`overflow: hidden;`导致超出的元素全部被隐藏了。

**Comment by hirCodd** [comment]
[http://123.207.36.91/](url) 这个是我改的样式，下拉那里已经改好了，只是还在本地修改着。
