### ISSUE TITLE
中英文切换

### ISSUE THREAD

**Issue by hirCodd** [QingdaoU/OnlineJudgeFE#22]
中英文切换的语言包已经基本写完了。picture如下：
用户端：
en:
![en.png](https://i.loli.net/2018/04/25/5ae037d8ecb3c.png)

zh:
![zh.png](https://i.loli.net/2018/04/25/5ae0383b0064a.png)

管理端：
en:
![en_admin.png](https://i.loli.net/2018/04/25/5ae0392bc1121.png)
zh:
![zh_admin.png](https://i.loli.net/2018/04/25/5ae0392bc2ab4.png)

**Comment by virusdefender** [comment]
麻烦问下，你是直接替换的字符串呢还是使用了 i18n 方案？

**Comment by virusdefender** [comment]
啊，看到了，在 pr

**Comment by hirCodd** [comment]
有一些东西，表格的东西，个人觉得是不用改成中文的，就oj使用者而言，基本能够读懂这些简单的英语。有一些翻译不是很准确，请谅解...

**Comment by zema1** [comment]
The code has been merged into master. Thanks for your pr. : )
