### ISSUE TITLE
NavBar在過窄的視窗無法完整顯示

### ISSUE THREAD

**Issue by xdavidwu** [QingdaoU/OnlineJudgeFE#24]
在一個13.3吋 1366x768的螢幕 瀏覽器用半塊螢幕時發現 NavBar 只能顯示到 Rank 
因為```#header```的```position: fixed;```無法橫向捲動
我初步的建議是改成```position: sticky;```

**Comment by zema1** [comment]
`postion: stricky;`这个属性对平台的兼容性比较差，而很多学校利用的都是旧版的chrome，所以不是很合适。
这个问题大概用 `@media`多写一份css`就可以解决。只是我不知道该怎么写比较好看，如果您有好的想法，可以pr一下，感谢。
