### ISSUE TITLE
在编写代码页面中，点击重置按钮无效

### ISSUE THREAD

**Issue by lizehongss** [QingdaoU/OnlineJudgeFE#38]

**Comment by lizehongss** [comment]
[代码链接](https://github.com/QingdaoU/OnlineJudgeFE/blob/9a50cd3ee610b4c9574917054429e3d2936b387b/src/pages/oj/views/problem/Problem.vue#L357)

**Comment by wangxinsheng0102** [comment]
[https://github.com/QingdaoU/OnlineJudgeFE/pull/53](url)
已修复
