### ISSUE TITLE
更新页面的标题

### ISSUE THREAD

**Issue by lazzzis** [QingdaoU/OnlineJudgeFE#5]
https://github.com/QingdaoU/OnlineJudgeFE/blob/aa9159dc6d8afacc8e1ce0659ca3f6167389d6f7/src/pages/oj/App.vue#L50

目前不论在哪个页面，页面的标题一直是 `Online Judge`，不会随页面更新。

后期是否会实现更新页面标题的功能？比如在 [https://qduoj.com/problem/1](https://qduoj.com/problem/1) 的时候能够显示 `Online Judge | A + B Problem`

**Comment by zema1** [comment]
这个功能用`vuex`来写会方便一些，我明天更新下

**Comment by lazzzis** [comment]
GJ!
![](https://i.loli.net/2017/12/10/5a2cad98856a0.jpg)
