### ISSUE TITLE
项目启动疯狂报错！！！

### ISSUE THREAD

**Issue by Pink-Smile** [QingdaoU/OnlineJudgeFE#75]
使用的一样的node版本，运行npm install 报错，之后的都运行不了！！！

**Comment by renbaoshuo** [comment]
报错内容截图看看，不截图就提 `issue` 哪能行

**Comment by Pink-Smile** [comment]
![image](https://user-images.githubusercontent.com/45811382/84965447-858fb600-b141-11ea-957f-586ed1a04b40.png)
不好意思！我是在windows下，clone项目后就运行npm install，之后报错，然后我把node版本改成一样的，还是这个错误。

**Comment by Pink-Smile** [comment]
我的问题解决了，原来是windows下命令使用不同导致的！

**Comment by iaeolous** [comment]
> 我的问题解决了，原来是windows下命令使用不同导致的！

请问你是如何解决的,我也是这个问题一直搞不好

**Comment by virusdefender** [comment]
windows 的试试 https://github.com/QingdaoU/OnlineJudgeFE/blob/master/README.md#windows

**Comment by Pink-Smile** [comment]
> > 我的问题解决了，原来是windows下命令使用不同导致的！
> 
> 请问你是如何解决的,我也是这个问题一直搞不好

README.md有更新，windows下方法有
