### ISSUE TITLE
npm build失败

### ISSUE THREAD

**Issue by iaeolous** [QingdaoU/OnlineJudgeFE#78]
node --version    v12.18.2
npm  --version    v6.14.5

npm run build报错信息:
![image](https://user-images.githubusercontent.com/17198878/88138284-f1bd7800-cc1f-11ea-96af-139ba97eb77d.png)

日志信息:
![image](https://user-images.githubusercontent.com/17198878/88138865-1a923d00-cc21-11ea-9cdf-36db3a03e447.png)

**Comment by virusdefender** [comment]
这个报错信息看不出来什么，可能没装 git？有可用信息再补充在本 issue 中就可以了

**Comment by iaeolous** [comment]
> 这个报错信息看不出来什么，可能没装 git？有可用信息再补充在本 issue 中就可以了

git有的啊,只有这些信息了。很苦恼，Windows和Linux都不行

**Comment by iaeolous** [comment]
我解决了，感谢 @virusdefender 提到的git让我想到了重新git clone 。重新git clone下项目就ok了，不知道为什么直接下项目zip不行
