### ISSUE TITLE
lot of warning when npm run dev 

### ISSUE THREAD

**Issue by smallst** [QingdaoU/OnlineJudgeFE#80]
```
 npm run dev

> onlinejudge@2.0.0 dev /home/smallst/work/CoCoOJ/CoCoOJFE
> node build/dev-server.js

current version is "20200805-a0cc3"
All entries:
oj
- ./src/pages/oj/index.js

admin
- ./src/pages/admin/index.js

[HPM] Proxy created: /api  ->  http://localhost/api
[HPM] Proxy created: /public  ->  http://localhost/api
> Starting dev server...
(node:11922) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11922) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:11922) Warning: Accessing non-existent property 'which' of module exports inside circular dependency



 DONE  Compiled successfully in 9638ms                                                                        1:32:35 PM
> Listening at http://localhost:8080

(node:11922) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/smallst/work/CoCoOJ/CoCoOJFE/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:673:12)
(node:11922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
是什么原因呢？依赖库版本比较旧？

**Comment by Harry-zklcdc** [comment]
应该是你的问题，我二次开发的时候不会这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tong Yuqiang"<notifications@github.com&gt;; 
发送时间: 2020年8月5日(星期三) 中午1:40
收件人: "QingdaoU/OnlineJudgeFE"<OnlineJudgeFE@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [QingdaoU/OnlineJudgeFE] lot of warning when npm run dev  (#80)





  npm run dev &gt; onlinejudge@2.0.0 dev /home/smallst/work/CoCoOJ/CoCoOJFE &gt; node build/dev-server.js current version is "20200805-a0cc3" All entries: oj - ./src/pages/oj/index.js admin - ./src/pages/admin/index.js [HPM] Proxy created: /api  -&gt;  http://localhost/api [HPM] Proxy created: /public  -&gt;  http://localhost/api &gt; Starting dev server... (node:11922) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency (Use `node --trace-warnings ...` to show where the warning was created) (node:11922) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'find' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'head' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'set' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'test' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'to' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'which' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'find' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'head' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'set' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'test' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'to' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency (node:11922) Warning: Accessing non-existent property 'which' of module exports inside circular dependency  DONE  Compiled successfully in 9638ms                                                                        1:32:35 PM &gt; Listening at http://localhost:8080 (node:11922) UnhandledPromiseRejectionWarning: Error: Exited with code 3     at ChildProcess.<anonymous&gt; (/home/smallst/work/CoCoOJ/CoCoOJFE/node_modules/opn/index.js:84:13)     at Object.onceWrapper (events.js:421:26)     at ChildProcess.emit (events.js:314:20)     at maybeClose (internal/child_process.js:1051:16)     at Socket.<anonymous&gt; (internal/child_process.js:442:11)     at Socket.emit (events.js:314:20)     at Pipe.<anonymous&gt; (net.js:673:12) (node:11922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:11922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
是什么原因呢？依赖库版本比较旧？

**Comment by smallst** [comment]
:joy: 行我自己再研究研究

**Comment by smallst** [comment]
downgrade node from v14 to v12 solve the warnings.
